using System;

namespace cv_5_ukol {
	public class Student : IComparable<Student> {
		public string OsCislo { get; set; }
		public string Jmeno { get; set; }
		public string Prijmeni { get; set; }
		public string UserName { get; set; }
		public int Rocnik { get; set; }
		public string OborKomb { get; set; }

		public override string ToString() {
			return $"{OsCislo}, {Jmeno}, {Prijmeni}, {UserName}, {Rocnik}, {OborKomb}";
		}

		public int CompareTo(Student s) {
			return Prijmeni.CompareTo(s.Prijmeni);
		}
	}

	public class ReadonlyDB {
		public static Student[] Students = {
		 new Student () {OsCislo="R18549",
Jmeno="Karim",
Prijmeni="AL KUHALY",
UserName="alkka00",
Rocnik=2,
OborKomb="APLINF"},
new Student () {OsCislo="R18128",
Jmeno="Jiří",
Prijmeni="BERAN",
UserName="beraji03",
Rocnik=2,
OborKomb="INF",
},
new Student () {OsCislo="R18556",
Jmeno="Daniel",
Prijmeni="DVOŘÁK",
UserName="dvorda10",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R180499",
Jmeno="Ruslan",
Prijmeni="DYSHLIUK",
UserName="dyshru00",
Rocnik=2,
OborKomb="INF",
},
new Student () {OsCislo="R180023",
Jmeno="Šimon",
Prijmeni="FIALA",
UserName="fialsi00",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18560",
Jmeno="Michael",
Prijmeni="HANZL",
UserName="hanzmi00",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18562",
Jmeno="Petr",
Prijmeni="JANČÁR",
UserName="jancpe03",
Rocnik=2,
OborKomb="APLINF",
},new Student () {OsCislo="R18101",
Jmeno="Petr",
Prijmeni="JANČÁR",
UserName="jancpe04",
Rocnik=3,
OborKomb="INF",
},
new Student () {OsCislo="R18133",
Jmeno="Ivana",
Prijmeni="JELÍNKOVÁ",
UserName="jeliiv01",
Rocnik=2,
OborKomb="INF",
},
new Student () {OsCislo="R18566",
Jmeno="Lukáš",
Prijmeni="JIŘÍČEK",
UserName="jirilu00",
Rocnik=2,
OborKomb="APLINF",
},new Student () {OsCislo="R18586",
Jmeno="Lukáš",
Prijmeni="JIŘÍČEK",
UserName="jirilu01",
Rocnik=1,
OborKomb="APLINF",
},
new Student () {OsCislo="R18571",
Jmeno="Petr",
Prijmeni="KOZÁK",
UserName="kozape03",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18573",
Jmeno="Jakub",
Prijmeni="KRBEC",
UserName="krbeja01",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18576",
Jmeno="Martin",
Prijmeni="KUREK",
UserName="kurema01",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18577",
Jmeno="David",
Prijmeni="KVĚTOŇ",
UserName="kvetda00",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18578",
Jmeno="Matěj",
Prijmeni="LÁNÍK",
UserName="lanima00",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R17729",
Jmeno="Lucia",
Prijmeni="MAHÚTOVÁ",
UserName="mahulu01",
Rocnik=3,
OborKomb="APLINF",
},
new Student () {OsCislo="R18585",
Jmeno="Vladimír",
Prijmeni="OPLUŠTIL",
UserName="opluvl00",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R17739",
Jmeno="Kateřina",
Prijmeni="PAVLOVSKÁ",
UserName="pavlka09",
Rocnik=3,
OborKomb="APLINF",
},
new Student () {OsCislo="R18139",
Jmeno="Kristína",
Prijmeni="POLÁKOVÁ",
UserName="polakr04",
Rocnik=2,
OborKomb="INF",
},
new Student () {OsCislo="R18588",
Jmeno="Martin",
Prijmeni="POPELKA",
UserName="popema06",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18592",
Jmeno="Martin",
Prijmeni="PŮDA",
UserName="pudama00",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18593",
Jmeno="Daniel",
Prijmeni="RÁBEL",
UserName="rabeda01",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18140",
Jmeno="Jakub",
Prijmeni="REŽŇÁK",
UserName="reznja03",
Rocnik=2,
OborKomb="INF",
},
new Student () {OsCislo="R18596",
Jmeno="Radim",
Prijmeni="SKOUPIL",
UserName="skoura00",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18597",
Jmeno="Jakub",
Prijmeni="SMÝKAL",
UserName="smykja00",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18599",
Jmeno="Radim",
Prijmeni="SOBĚHART",
UserName="sobera00",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18601",
Jmeno="Daniel",
Prijmeni="STONAWSKI",
UserName="stonda00",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18602",
Jmeno="Petr",
Prijmeni="SUCHÁNEK",
UserName="suchpe02",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18606",
Jmeno="Miroslav",
Prijmeni="ŠTEFKA",
UserName="stefmi07",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18608",
Jmeno="Marek",
Prijmeni="TREFIL",
UserName="trefma01",
Rocnik=2,
OborKomb="APLINF",
},
new Student () {OsCislo="R18611",
Jmeno="Jaroslav",
Prijmeni="VEČEŘA",
UserName="veceja06",
Rocnik=2,
		OborKomb="APLINF"}

	};
	}
}


