//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 9.4.2020 14:26:15
namespace cv_8_backed.Models
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Product> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<Product>("Products");
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Product> _Products;
        /// <summary>
        /// There are no comments for PriceHistory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PriceHistoryEntry> PriceHistory
        {
            get
            {
                if ((this._PriceHistory == null))
                {
                    this._PriceHistory = base.CreateQuery<PriceHistoryEntry>("PriceHistory");
                }
                return this._PriceHistory;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PriceHistoryEntry> _PriceHistory;
        /// <summary>
        /// There are no comments for PurchaseHistory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PurchaseHistoryEntry> PurchaseHistory
        {
            get
            {
                if ((this._PurchaseHistory == null))
                {
                    this._PurchaseHistory = base.CreateQuery<PurchaseHistoryEntry>("PurchaseHistory");
                }
                return this._PurchaseHistory;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PurchaseHistoryEntry> _PurchaseHistory;
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
        /// <summary>
        /// There are no comments for PriceHistory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPriceHistory(PriceHistoryEntry priceHistoryEntry)
        {
            base.AddObject("PriceHistory", priceHistoryEntry);
        }
        /// <summary>
        /// There are no comments for PurchaseHistory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPurchaseHistory(PurchaseHistoryEntry purchaseHistoryEntry)
        {
            base.AddObject("PurchaseHistory", purchaseHistoryEntry);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"cv_8_backed.Models\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/e" +
                "dm\"><EntityType Name=\"Product\"><Key><PropertyRef Name=\"Id\" /></Key><Property Nam" +
                "e=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.Strin" +
                "g\" /><NavigationProperty Name=\"PriceHistory\" Relationship=\"cv_8_backed.Models.cv" +
                "__8__backed_Models_Product_PriceHistory_cv__8__backed_Models_PriceHistoryEntry_P" +
                "riceHistoryPartner\" ToRole=\"PriceHistory\" FromRole=\"PriceHistoryPartner\" /><Navi" +
                "gationProperty Name=\"PurchaseHistory\" Relationship=\"cv_8_backed.Models.cv__8__ba" +
                "cked_Models_Product_PurchaseHistory_cv__8__backed_Models_PurchaseHistoryEntry_Pu" +
                "rchaseHistoryPartner\" ToRole=\"PurchaseHistory\" FromRole=\"PurchaseHistoryPartner\"" +
                " /></EntityType><EntityType Name=\"PriceHistoryEntry\"><Key><PropertyRef Name=\"Id\"" +
                " /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=" +
                "\"Date\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"Price\" Type=\"Edm.D" +
                "ecimal\" Nullable=\"false\" /></EntityType><EntityType Name=\"PurchaseHistoryEntry\">" +
                "<Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullabl" +
                "e=\"false\" /><Property Name=\"Date\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Proper" +
                "ty Name=\"CustomerName\" Type=\"Edm.String\" /></EntityType><Association Name=\"cv__8" +
                "__backed_Models_Product_PriceHistory_cv__8__backed_Models_PriceHistoryEntry_Pric" +
                "eHistoryPartner\"><End Type=\"cv_8_backed.Models.PriceHistoryEntry\" Role=\"PriceHis" +
                "tory\" Multiplicity=\"*\" /><End Type=\"cv_8_backed.Models.Product\" Role=\"PriceHisto" +
                "ryPartner\" Multiplicity=\"0..1\" /></Association><Association Name=\"cv__8__backed_" +
                "Models_Product_PurchaseHistory_cv__8__backed_Models_PurchaseHistoryEntry_Purchas" +
                "eHistoryPartner\"><End Type=\"cv_8_backed.Models.PurchaseHistoryEntry\" Role=\"Purch" +
                "aseHistory\" Multiplicity=\"*\" /><End Type=\"cv_8_backed.Models.Product\" Role=\"Purc" +
                "haseHistoryPartner\" Multiplicity=\"0..1\" /></Association></Schema><Schema Namespa" +
                "ce=\"Default\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityContain" +
                "er Name=\"Container\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Products\"" +
                " EntityType=\"cv_8_backed.Models.Product\" /><EntitySet Name=\"PriceHistory\" Entity" +
                "Type=\"cv_8_backed.Models.PriceHistoryEntry\" /><EntitySet Name=\"PurchaseHistory\" " +
                "EntityType=\"cv_8_backed.Models.PurchaseHistoryEntry\" /><AssociationSet Name=\"cv_" +
                "_8__backed_Models_Product_PriceHistory_cv__8__backed_Models_PriceHistoryEntry_Pr" +
                "iceHistoryPartnerSet\" Association=\"cv_8_backed.Models.cv__8__backed_Models_Produ" +
                "ct_PriceHistory_cv__8__backed_Models_PriceHistoryEntry_PriceHistoryPartner\"><End" +
                " Role=\"PriceHistoryPartner\" EntitySet=\"Products\" /><End Role=\"PriceHistory\" Enti" +
                "tySet=\"PriceHistory\" /></AssociationSet><AssociationSet Name=\"cv__8__backed_Mode" +
                "ls_Product_PurchaseHistory_cv__8__backed_Models_PurchaseHistoryEntry_PurchaseHis" +
                "toryPartnerSet\" Association=\"cv_8_backed.Models.cv__8__backed_Models_Product_Pur" +
                "chaseHistory_cv__8__backed_Models_PurchaseHistoryEntry_PurchaseHistoryPartner\"><" +
                "End Role=\"PurchaseHistoryPartner\" EntitySet=\"Products\" /><End Role=\"PurchaseHist" +
                "ory\" EntitySet=\"PurchaseHistory\" /></AssociationSet></EntityContainer></Schema><" +
                "/edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for cv_8_backed.Models.Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Product
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Product CreateProduct(int ID)
        {
            Product product = new Product();
            product.Id = ID;
            return product;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for PriceHistory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<PriceHistoryEntry> PriceHistory
        {
            get
            {
                return this._PriceHistory;
            }
            set
            {
                if ((value != null))
                {
                    this._PriceHistory = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<PriceHistoryEntry> _PriceHistory = new global::System.Collections.ObjectModel.Collection<PriceHistoryEntry>();
        /// <summary>
        /// There are no comments for PurchaseHistory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<PurchaseHistoryEntry> PurchaseHistory
        {
            get
            {
                return this._PurchaseHistory;
            }
            set
            {
                if ((value != null))
                {
                    this._PurchaseHistory = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<PurchaseHistoryEntry> _PurchaseHistory = new global::System.Collections.ObjectModel.Collection<PurchaseHistoryEntry>();
    }
    /// <summary>
    /// There are no comments for cv_8_backed.Models.PriceHistoryEntry in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PriceHistoryEntry
    {
        /// <summary>
        /// Create a new PriceHistoryEntry object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="price">Initial value of Price.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PriceHistoryEntry CreatePriceHistoryEntry(int ID, global::System.DateTime date, decimal price)
        {
            PriceHistoryEntry priceHistoryEntry = new PriceHistoryEntry();
            priceHistoryEntry.Id = ID;
            priceHistoryEntry.Date = date;
            priceHistoryEntry.Price = price;
            return priceHistoryEntry;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Price;
        partial void OnPriceChanging(decimal value);
        partial void OnPriceChanged();
    }
    /// <summary>
    /// There are no comments for cv_8_backed.Models.PurchaseHistoryEntry in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PurchaseHistoryEntry
    {
        /// <summary>
        /// Create a new PurchaseHistoryEntry object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PurchaseHistoryEntry CreatePurchaseHistoryEntry(int ID, global::System.DateTime date)
        {
            PurchaseHistoryEntry purchaseHistoryEntry = new PurchaseHistoryEntry();
            purchaseHistoryEntry.Id = ID;
            purchaseHistoryEntry.Date = date;
            return purchaseHistoryEntry;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property CustomerName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CustomerName
        {
            get
            {
                return this._CustomerName;
            }
            set
            {
                this.OnCustomerNameChanging(value);
                this._CustomerName = value;
                this.OnCustomerNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CustomerName;
        partial void OnCustomerNameChanging(string value);
        partial void OnCustomerNameChanged();
    }
}
