//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 9.4.2020 19:44:24
namespace cv_8_backed.Models
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Product> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<Product>("Products");
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Product> _Products;
        /// <summary>
        /// There are no comments for PriceHistoryEntries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PriceHistoryEntry> PriceHistoryEntries
        {
            get
            {
                if ((this._PriceHistoryEntries == null))
                {
                    this._PriceHistoryEntries = base.CreateQuery<PriceHistoryEntry>("PriceHistoryEntries");
                }
                return this._PriceHistoryEntries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PriceHistoryEntry> _PriceHistoryEntries;
        /// <summary>
        /// There are no comments for PurchaseHistoryEntries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PurchaseHistoryEntry> PurchaseHistoryEntries
        {
            get
            {
                if ((this._PurchaseHistoryEntries == null))
                {
                    this._PurchaseHistoryEntries = base.CreateQuery<PurchaseHistoryEntry>("PurchaseHistoryEntries");
                }
                return this._PurchaseHistoryEntries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PurchaseHistoryEntry> _PurchaseHistoryEntries;
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
        /// <summary>
        /// There are no comments for PriceHistoryEntries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPriceHistoryEntries(PriceHistoryEntry priceHistoryEntry)
        {
            base.AddObject("PriceHistoryEntries", priceHistoryEntry);
        }
        /// <summary>
        /// There are no comments for PurchaseHistoryEntries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPurchaseHistoryEntries(PurchaseHistoryEntry purchaseHistoryEntry)
        {
            base.AddObject("PurchaseHistoryEntries", purchaseHistoryEntry);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"cv_8_backed.Models\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/e" +
                "dm\"><EntityType Name=\"Product\"><Key><PropertyRef Name=\"Id\" /></Key><Property Nam" +
                "e=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.Strin" +
                "g\" /><NavigationProperty Name=\"PriceHistory\" Relationship=\"cv_8_backed.Models.cv" +
                "__8__backed_Models_Product_PriceHistory_cv__8__backed_Models_PriceHistoryEntry_P" +
                "riceHistoryPartner\" ToRole=\"PriceHistory\" FromRole=\"PriceHistoryPartner\" /><Navi" +
                "gationProperty Name=\"PurchaseHistory\" Relationship=\"cv_8_backed.Models.cv__8__ba" +
                "cked_Models_Product_PurchaseHistory_cv__8__backed_Models_PurchaseHistoryEntry_Pu" +
                "rchaseHistoryPartner\" ToRole=\"PurchaseHistory\" FromRole=\"PurchaseHistoryPartner\"" +
                " /></EntityType><EntityType Name=\"PriceHistoryEntry\"><Key><PropertyRef Name=\"Id\"" +
                " /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=" +
                "\"ProductId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Date\" Type=\"Edm." +
                "DateTime\" Nullable=\"false\" /><Property Name=\"Price\" Type=\"Edm.Decimal\" Nullable=" +
                "\"false\" /></EntityType><EntityType Name=\"PurchaseHistoryEntry\"><Key><PropertyRef" +
                " Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Prop" +
                "erty Name=\"ProductId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Date\" " +
                "Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"CustomerName\" Type=\"Edm.S" +
                "tring\" /></EntityType><Association Name=\"cv__8__backed_Models_Product_PriceHisto" +
                "ry_cv__8__backed_Models_PriceHistoryEntry_PriceHistoryPartner\"><End Type=\"cv_8_b" +
                "acked.Models.PriceHistoryEntry\" Role=\"PriceHistory\" Multiplicity=\"*\" /><End Type" +
                "=\"cv_8_backed.Models.Product\" Role=\"PriceHistoryPartner\" Multiplicity=\"0..1\" /><" +
                "/Association><Association Name=\"cv__8__backed_Models_Product_PurchaseHistory_cv_" +
                "_8__backed_Models_PurchaseHistoryEntry_PurchaseHistoryPartner\"><End Type=\"cv_8_b" +
                "acked.Models.PurchaseHistoryEntry\" Role=\"PurchaseHistory\" Multiplicity=\"*\" /><En" +
                "d Type=\"cv_8_backed.Models.Product\" Role=\"PurchaseHistoryPartner\" Multiplicity=\"" +
                "0..1\" /></Association></Schema><Schema Namespace=\"Default\" xmlns=\"http://schemas" +
                ".microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"Container\" m:IsDefaultEnt" +
                "ityContainer=\"true\"><EntitySet Name=\"Products\" EntityType=\"cv_8_backed.Models.Pr" +
                "oduct\" /><EntitySet Name=\"PriceHistoryEntries\" EntityType=\"cv_8_backed.Models.Pr" +
                "iceHistoryEntry\" /><EntitySet Name=\"PurchaseHistoryEntries\" EntityType=\"cv_8_bac" +
                "ked.Models.PurchaseHistoryEntry\" /><AssociationSet Name=\"cv__8__backed_Models_Pr" +
                "oduct_PriceHistory_cv__8__backed_Models_PriceHistoryEntry_PriceHistoryPartnerSet" +
                "\" Association=\"cv_8_backed.Models.cv__8__backed_Models_Product_PriceHistory_cv__" +
                "8__backed_Models_PriceHistoryEntry_PriceHistoryPartner\"><End Role=\"PriceHistoryP" +
                "artner\" EntitySet=\"Products\" /><End Role=\"PriceHistory\" EntitySet=\"PriceHistoryE" +
                "ntries\" /></AssociationSet><AssociationSet Name=\"cv__8__backed_Models_Product_Pu" +
                "rchaseHistory_cv__8__backed_Models_PurchaseHistoryEntry_PurchaseHistoryPartnerSe" +
                "t\" Association=\"cv_8_backed.Models.cv__8__backed_Models_Product_PurchaseHistory_" +
                "cv__8__backed_Models_PurchaseHistoryEntry_PurchaseHistoryPartner\"><End Role=\"Pur" +
                "chaseHistoryPartner\" EntitySet=\"Products\" /><End Role=\"PurchaseHistory\" EntitySe" +
                "t=\"PurchaseHistoryEntries\" /></AssociationSet></EntityContainer></Schema></edmx:" +
                "DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for cv_8_backed.Models.Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Product
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Product CreateProduct(int ID)
        {
            Product product = new Product();
            product.Id = ID;
            return product;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for PriceHistory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<PriceHistoryEntry> PriceHistory
        {
            get
            {
                return this._PriceHistory;
            }
            set
            {
                if ((value != null))
                {
                    this._PriceHistory = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<PriceHistoryEntry> _PriceHistory = new global::System.Collections.ObjectModel.Collection<PriceHistoryEntry>();
        /// <summary>
        /// There are no comments for PurchaseHistory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<PurchaseHistoryEntry> PurchaseHistory
        {
            get
            {
                return this._PurchaseHistory;
            }
            set
            {
                if ((value != null))
                {
                    this._PurchaseHistory = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<PurchaseHistoryEntry> _PurchaseHistory = new global::System.Collections.ObjectModel.Collection<PurchaseHistoryEntry>();
    }
    /// <summary>
    /// There are no comments for cv_8_backed.Models.PriceHistoryEntry in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PriceHistoryEntry
    {
        /// <summary>
        /// Create a new PriceHistoryEntry object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="productId">Initial value of ProductId.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="price">Initial value of Price.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PriceHistoryEntry CreatePriceHistoryEntry(int ID, int productId, global::System.DateTime date, decimal price)
        {
            PriceHistoryEntry priceHistoryEntry = new PriceHistoryEntry();
            priceHistoryEntry.Id = ID;
            priceHistoryEntry.ProductId = productId;
            priceHistoryEntry.Date = date;
            priceHistoryEntry.Price = price;
            return priceHistoryEntry;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ProductId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProductId
        {
            get
            {
                return this._ProductId;
            }
            set
            {
                this.OnProductIdChanging(value);
                this._ProductId = value;
                this.OnProductIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProductId;
        partial void OnProductIdChanging(int value);
        partial void OnProductIdChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Price;
        partial void OnPriceChanging(decimal value);
        partial void OnPriceChanged();
    }
    /// <summary>
    /// There are no comments for cv_8_backed.Models.PurchaseHistoryEntry in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PurchaseHistoryEntry
    {
        /// <summary>
        /// Create a new PurchaseHistoryEntry object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="productId">Initial value of ProductId.</param>
        /// <param name="date">Initial value of Date.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PurchaseHistoryEntry CreatePurchaseHistoryEntry(int ID, int productId, global::System.DateTime date)
        {
            PurchaseHistoryEntry purchaseHistoryEntry = new PurchaseHistoryEntry();
            purchaseHistoryEntry.Id = ID;
            purchaseHistoryEntry.ProductId = productId;
            purchaseHistoryEntry.Date = date;
            return purchaseHistoryEntry;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ProductId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProductId
        {
            get
            {
                return this._ProductId;
            }
            set
            {
                this.OnProductIdChanging(value);
                this._ProductId = value;
                this.OnProductIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProductId;
        partial void OnProductIdChanging(int value);
        partial void OnProductIdChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property CustomerName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CustomerName
        {
            get
            {
                return this._CustomerName;
            }
            set
            {
                this.OnCustomerNameChanging(value);
                this._CustomerName = value;
                this.OnCustomerNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CustomerName;
        partial void OnCustomerNameChanging(string value);
        partial void OnCustomerNameChanged();
    }
}
